# Generated by Django 5.0.1 on 2024-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
